services:
  socket:
    build: ./socket
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

  next:
    build: ./next
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://socket:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
