# 개발용 Docker Compose 오버라이드
version: '3.8'

services:
  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile.dev
    volumes:
      - ./socket:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  next:
    build:
      context: ./next
      dockerfile: Dockerfile.dev
    volumes:
      - ./next:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development