version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  socket:
    image: ${ECR_REGISTRY}/${ECR_REPO_SOCKET}:${IMAGE_TAG}
    ports:
      - "${EC2_HOST_SOCKET:-3001}:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - EC2_HOST_NEXT=${EC2_HOST_NEXT}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - REDIS_URL=${REDIS_URL}
      - ECR_REGISTRY=${ECR_REGISTRY}
      - ECR_REPO_SOCKET=${ECR_REPO_SOCKET}
      - IMAGE_TAG=latest
    restart: unless-stopped