services:
  socket:
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  next:
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://socket:3001
      - NEXT_PUBLIC_BASE_URL=https://wheretoput.store
      - AUTH_TRUST_HOST=true
    networks:
      - app-network
    volumes:
      - ./next:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
