FROM node:22-alpine

RUN apk add --no-cache libc6-compat && \
    rm -rf /var/cache/apk/*

WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json* ./
RUN npm ci --no-audit --no-fund && \
    npm cache clean --force && \
    npm prune && \
    rm -rf /root/.npm /tmp/*

COPY prisma ./prisma/
RUN npx prisma generate

# node_modules만 제외하고 모든 소스 복사
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]