name: wheretoput_CI

on:
  pull_request:
    branches: ["dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.*
          cache: npm
          cache-dependency-path: |
            next/package-lock.json
            socket/package-lock.json

      # --- Next.js(Web) ---
      - name: Install deps (next)
        run: npm ci
        working-directory: next/

      - name: Lint (next)
        run: npm run lint --if-present
        working-directory: next/

      - name: Test (next)
        run: npm test --if-present -- --ci
        working-directory: next/

      - name: Build (next)
        run: npm run build
        working-directory: next/

      # --- NestJS(Socket) ---
      - name: Install deps (socket)
        run: npm ci
        working-directory: socket/

      - name: Lint (socket)
        run: npm run lint --if-present # 린트 실패해도 계속 진행 # || true 지우면 정상 테스트
        working-directory: socket/

      - name: Test (socket)
        run: npm test --if-present -- --ci
        working-directory: socket/

      - name: Build (socket)
        run: npm run build
        working-directory: socket/

  docker-build-check:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      # Next.js (web)
      - name: Build web image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./next
          file: ./next/Dockerfile.dev   # 개발용이면 dev Dockerfile 지정 가능
          push: false
          tags: next:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
      # NestJS (socket)
      - name: Build api image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./socket
          file: ./socket/Dockerfile.dev
          push: false
          tags: socket:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
