name: CD — deploy on dev→main merge

on:
  pull_request:
    branches: ["main"]
    types: [closed]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPO_NEXT: ${{ secrets.ECR_REPO_NEXT }}
  ECR_REPO_SOCKET: ${{ secrets.ECR_REPO_SOCKET }}
  IMAGE_TAG: ${{ github.sha }}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    if: >-
      ${{ github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'main' &&
          github.event.pull_request.head.ref == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push Next.js image
        uses: docker/build-push-action@v6
        with:
          context: next
          file: next/Dockerfile.prod  # 추가
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NEXT }}:${{ github.sha }}
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NEXT }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push NestJS image
        uses: docker/build-push-action@v6
        with:
          context: socket
          file: socket/Dockerfile.prod  # 추가
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_SOCKET }}:${{ github.sha }}
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_SOCKET }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-next:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Next.js .env.production
        run: |
          cat > .env.production << 'EOF'
          NODE_ENV=production
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}
          ECR_REPO_NEXT=${{ secrets.ECR_REPO_NEXT }}
          IMAGE_TAG=${{ github.sha }}
          FRONTEND_PORT=3000
          AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }}
          AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}
          REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }}
          NEXTAUTH_SECRET=${{ secrets.JWT_SECRET }}
          AUTH_TRUST_HOST=true
          NEXT_PUBLIC_BASE_URL=http://${{ secrets.EC2_HOST_NEXT }}:3000
          EOF

      - name: Upload files to Next.js EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_NEXT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_NEXT }}
          source: "docker-compose.next.yml,.env.production"
          target: ${{ secrets.EC2_DEPLOY_PATH }}/next/
          timeout: 60s

      - name: Deploy Next.js on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_NEXT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_NEXT }}
          script: |
            docker system prune -f
            set -e
            cd ${{ secrets.EC2_DEPLOY_PATH }}/next
            
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
              docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
            
            export IMAGE_TAG=${{ github.sha }}
            export ECR_REGISTRY=${{ env.ECR_REGISTRY }}
            export ECR_REPO_NEXT=${{ secrets.ECR_REPO_NEXT }}
            
            docker-compose -f docker-compose.next.yml --env-file .env.production pull
            docker-compose -f docker-compose.next.yml --env-file .env.production up -d --remove-orphans
            docker image prune -f

  deploy-nest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create NestJS .env.production
        run: |
          cat > .env.production << 'EOF'
          NODE_ENV=production
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EC2_HOST_NEXT=$ {{ secrets.EC2_HOST_NEXT }}
          EOF

      - name: Upload files to NestJS EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_SOCKET }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_SOCKET }}
          source: "docker-compose.socket.yml,.env.production"
          target: ${{ secrets.EC2_DEPLOY_PATH }}/socket/
          timeout: 60s
      
      - name: Deploy NestJS on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_SOCKET }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_SOCKET }}
          script: |
            docker system prune -f
            set -e
            cd ${{ secrets.EC2_DEPLOY_PATH }}/socket
            
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
              docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
            
            export IMAGE_TAG=${{ github.sha }}
            export ECR_REGISTRY=${{ env.ECR_REGISTRY }}
            export ECR_REPO_SOCKET=${{ secrets.ECR_REPO_SOCKET }}
            
            docker-compose -f docker-compose.socket.yml --env-file .env.production pull
            docker-compose -f docker-compose.socket.yml --env-file .env.production up -d --remove-orphans
            docker image prune -f
            
            if docker-compose -f docker-compose.socket.yml ps socket >/dev/null 2>&1; then
              docker-compose -f docker-compose.socket.yml --env-file .env.production run --rm socket npx prisma migrate deploy || true
            fi
